<?php

namespace Mapes\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderEntryRepository extends EntityRepository
{
}
