<?php

namespace Mapes\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NavigationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NavigationRepository extends EntityRepository
{
    
    public function getNavElements($location, $element_type, $parent_id = NULL)
    {
        $qb = $this->createQueryBuilder('j')
          ->where('j.location = :location')
          ->setParameter('location', $location)
          ->Andwhere('j.element_type = :element_type')
          ->setParameter('element_type', $element_type)
          ->orderBy('j.order_num', 'ASC');

        if($parent_id)
        {
          $qb->andWhere('j.parent_id = :parent_id')
             ->setParameter('parent_id', $parent_id);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }    
    
    public function deleteNavElements($location)
    {
        $isDeleted = $this->createQueryBuilder("j")
            ->delete()
            ->where('j.location  = :location')->setParameter("location", $location)
            ->getQuery()->execute();

        return $isDeleted;
    }
}
