<?php

namespace Mapes\CMSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageImageRepository extends EntityRepository
{
    public function getPageImageByFilePath($file_path)
    {
        $query = $this->createQueryBuilder('j')
          ->where('j.file_path = :file_path')
          ->setParameter('file_path', $file_path)
          ->setMaxResults(1)
          ->getQuery();

        try {
          $page_image = $query->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
          $page_image = null;
        }

        return $page_image;
        
    }
}
