parameters:
#    mapes_shop.example.class: Mapes\ShopBundle\Example

services:
#    mapes_shop.example:
#        class: %mapes_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    mapes_shop.admin.product:
        class: Mapes\ShopBundle\Admin\ProductAdmin
        arguments: [~, Mapes\ShopBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Shop, label: Product}
    #eWay helper
    eway_helper:
        class:  Mapes\ShopBundle\Utils\eWayUtils
        arguments: ["@kernel", "@doctrine.orm.default_entity_manager"]