#Sonata Admin Bundle    
sonata_admin:
    title: Demo
    title_logo: bundles/mapescms/images/maple_leaves_sm.jpeg
    options:
        html5_validate:            true  
        use_select2:               false
        use_icheck:                false
    templates:
        # default global templates
        #layout:  SonataAdminBundle::standard_layout.html.twig
        layout:  ::admin.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        dashboard: SonataAdminBundle:Core:dashboard.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        user_block: MapesUserBundle:Block:user_block.html.twig
        
    dashboard:
        blocks:
            - { position: top, class: col-md-6, type: sonata.block.service.text, settings: {content : "<h2>Admin Dashboard</h2>"}}
            
            - { position: right, type: sonata.member.block.recent_members, settings: {} }
            
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

            # Customize this part to add new block configuration
            #- { position: right, type: sonata.block.service.text, settings: {content : "<h2>Welcome to the CMS Admin</h2>"} }
            # - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the CMS Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):"} }
            #- { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}    
            
        groups:
            sonata.admin.group.content:
                label:           Content
                label_catalogue: MapesCMSBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - mapes_cms.admin.page

            sonata.admin.group.interaction:
                label:           Interaction
                label_catalogue: MapesCustomFormBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - mapes_custom_form.admin.custom_form
                    - mapes_custom_form.admin.custom_form_entry

            sonata.admin.group.shop:
                label:           Shop
                label_catalogue: MapesShopBundle
                icon:            '<i class="fa fa-dollar"></i>'
                items:
                    - mapes_shop.admin.product

            sonata.admin.group.administration:
                label:           Administration
                label_catalogue: MapesUserBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                   - mapes_cms.admin.member
                   - mapes_cms.admin.newsletter
            #sonata.admin.group.seo:
            #    label:           SEO
            #    label_catalogue: MapesCMSBundle
            #    icon:            '<i class="fa fa-cogs"></i>'
            #    items:
            #    - mapes_cms.admin.redirect
    # set to true to persist filter settings per admin module in the user's session
    #persist_filters: false        

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:    
        sonata.member.block.recent_members: