Mapes\UserBundle\Entity\Member:
  type: entity
  repositoryClass: Mapes\UserBundle\Repository\MemberRepository
  table: member
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    first_name:
      type: string
      length: 255
      nullable: true
    last_name:
      type: string
      length: 255
      nullable: true
    username:
      type: string
      length: 255
      nullable: true
    email:
      type: string
      length: 255
      nullable: true
    plain_password:
      type: string
      length: 255
      nullable: true
    password:
      type: string
      length: 255
      nullable: true
    is_activated:
      type: boolean
      nullable: true
    created_at:
      type: datetime
      nullable: true
    account_type:
      type: string
      length: 255
      nullable: true
    user_type:
      type: string
      length: 255
      nullable: true
    phone:
      type: string
      length: 255
      nullable: true
    photo:
      type: string
      length: 255
      nullable: true
    email_hash:
      type: string
      length: 255
      nullable: true
  manyToMany:
    newsletters:
      targetEntity: Newsletter
      joinTable:
        name: member_newsletter
        joinColumns:
          member_id:
            referencedColumnName: id
        inverseJoinColumns:
          newsletter_id:
            referencedColumnName: id      
  lifecycleCallbacks:
    prePersist: [ preUploadPhoto, setCreatedAtValue, setPasswordValue]
    preUpdate: [ preUploadPhoto, setPasswordValue ]
    postPersist: [ uploadPhoto ]
    postUpdate: [ uploadPhoto ]
    postRemove: [ removeUploadPhoto ]