Mapes\UserBundle\Entity\Newsletter:
  type: entity
  repositoryClass: Mapes\UserBundle\Repository\NewsletterRepository
  table: newsletter
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      nullable: true
  manyToMany:
    members:
      targetEntity: Member
      mappedBy: newsletters
  lifecycleCallbacks:
    prePersist: []
    preUpdate: []
