<?php

namespace Mapes\CustomFormBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomFormEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomFormEntryRepository extends EntityRepository
{

}
